trigger:
- release/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: 'src/bifröst.sln'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'

- task: DotNetCoreCLI@2
  displayName: 'restore'
  inputs:
    command: 'restore'
    projects: $(solution)
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'build'
  inputs:
    command: 'build'
    configuration: $(buildConfiguration)
    projects: $(solution)

- task: DotNetCoreCLI@2
  displayName: 'test'
  inputs:
    command: 'test'
    configuration: $(buildConfiguration)
    projects: $(solution)

- task: CopyFiles@2
  inputs:
    Contents: '**/*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'nuget'
    publishLocation: 'Container'