name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: build
      run: dotnet build src/bifröst.sln --configuration Release
    - name: test
      run: dotnet test src/bifröst.sln --logger trx
    - name: upload test results
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: test results
        # Directory containing files to upload
        path: /**/*.trx
